name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'
      - '.github/workflows/container.yml'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Action AWS CLI
        uses: shinyinc/action-aws-cli@v1.2

      - name: Deploy to S3
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create invalidation
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${‌{ secrets.AWS_DISTRIBUTION_ID }}
          AWS_REGION: 'eu-north-1'
          PATHS: '/container/latest/index.html'
          AWS_ACCESS_KEY_ID: ${‌{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${‌{ secrets.AWS_SECRET_ACCESS_KEY }}
